// Is the committed code map current for the source that is actually here?
//
// `#205 (FORGE-266)`. The map's own header tells a reader to compare its stamp
// against `git log -1 -- <indexed globs>` and regenerate if they differ. That check
// is right about drift and **wrong about squash merges**, which is the case it meets
// most often: the repository standard requires the map to be restamped in the same
// PR as any source change that moves a symbol, and a squash collapses that PR's
// source commit and its map commit into one new SHA. The map can only ever name a
// commit that precedes its own, so the stamp is orphaned the moment it lands.
//
// Measured six times between 2026-09-02 and 2026-09-04, every one a false positive:
// the anchors were correct and only the stamp was unreachable. A freshness signal
// that cries wolf six times in three days is one a session learns to reason around,
// which is the failure this file exists to end.
//
// So the authority moves from the stamp to the content. This regenerates the map
// from the working tree and requires it to match what is committed, ignoring only
// the two header lines that carry the date and the commit. A stamp mismatch after a
// squash is expected and harmless; an anchor mismatch is real and fails here.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { emptyDir } from './helpers/make-repo.mjs';
import { main } from '../scripts/code-map.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/** The generated file minus its provenance. Line 4 carries the date and line 5 the
 *  commit; both are facts about *when* the map was made rather than about what it
 *  says, and neither can survive a squash. Everything else — every file, size, line
 *  count and anchor — is content and is compared exactly. */
function withoutProvenance(text) {
  return text
    .split('\n')
    .filter((line) => !line.startsWith('Generated by `scripts/code-map.mjs` on ')
      && !line.startsWith('source as of commit `'))
    .join('\n');
}

test('the committed code map matches a fresh regeneration of this working tree', () => {
  // The assertion the stamp comparison was standing in for. If this passes, every
  // anchor in `docs/code-map.md` points where it claims to, whatever the stamp says.
  const out = join(emptyDir(), 'code-map.md');
  assert.equal(main(['node', 'code-map.mjs', ROOT, '--out', out]), 0, 'the generator did not run');

  const fresh = withoutProvenance(readFileSync(out, 'utf8'));
  const committed = withoutProvenance(readFileSync(join(ROOT, 'docs', 'code-map.md'), 'utf8'));

  // Located rather than dumped: two 60KB blobs in an assertion message tell a reader
  // nothing, and the first differing line is the file whose anchors moved.
  if (fresh !== committed) {
    const a = fresh.split('\n');
    const b = committed.split('\n');
    const at = a.findIndex((line, i) => line !== b[i]);
    assert.fail(
      'docs/code-map.md is stale — a symbol moved and the map was not regenerated.\n'
      + `First difference at line ${at + 1}:\n`
      + `  committed: ${b[at] ?? '<end of file>'}\n`
      + `  regenerated: ${a[at] ?? '<end of file>'}\n`
      + 'Fix: node scripts/code-map.mjs . — and commit it in the same PR as the source change.',
    );
  }
  assert.equal(fresh, committed);
});

test('the map explains that its stamp does not survive a squash merge', () => {
  // The header is what a session reads before deciding whether to trust an anchor,
  // and it previously said a differing stamp meant the map was stale full stop.
  // Six false positives came from believing it. The correction has to live where
  // that reader arrives, not only in this file.
  //
  // Mutation killed: restoring the old unqualified wording, which leaves the header
  // telling a reader to regenerate a map that is already correct.
  const map = readFileSync(join(ROOT, 'docs', 'code-map.md'), 'utf8');
  // The claim itself, not a keyword. `/squash/i` was the first draft and it
  // survived its own mutant: the word appears in three places here, so deleting
  // the sentence that carries the correction left the assertion green. What a
  // reader needs is the retraction, so that is what is asserted.
  assert.match(map, /A differing stamp is not proof of staleness/,
    'the header does not retract the claim that a differing stamp means stale');
  assert.match(map, /squash merge/i, 'the header never names the case that orphans its stamp');
  assert.match(map, /tests\/code-map-freshness\.test\.mjs/,
    'the header does not name the check that actually settles freshness');
});
