import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { makeRepo, emptyDir } from './helpers/make-repo.mjs';
import { scaffold } from '../scripts/scaffold.mjs';
import {
  LIBRARY_ROOT, ITEM_FIELDS, items, parseFrontmatter, checkItems,
  INDEX_PATH, buildIndex, checkIndex, validateLibrary,
} from '../profiles/content-library/files/scripts/validate-library.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const values = (name) => ({
  year: 2026,
  tokens: { PROJECT_NAME: name, PROJECT_SUMMARY: 'A throwaway scaffold used to verify daftplate.' },
});

const ITEM = (title, category, summary = 'A short line.') =>
  `---\ntitle: ${title}\ncategory: ${category}\nsummary: ${summary}\nupdated: 2026-07-22\n---\n\nBody.\n`;

// --- Task 3c.1: the item schema ---

test('LIBRARY_ROOT and ITEM_FIELDS are the contract', () => {
  assert.equal(LIBRARY_ROOT, 'library');
  assert.deepEqual(ITEM_FIELDS, ['title', 'category', 'summary', 'updated']);
});

test('items lists markdown under library/ and ignores everything else', () => {
  const root = makeRepo({
    'library/finance/close-the-month.md': ITEM('Close the month', 'finance'),
    'library/finance/notes.txt': 'not an item',
    'templates/item.md': ITEM('Template', 'none'),
    'docs/library-index.md': '# index\n',
  });

  assert.deepEqual(items(root), ['library/finance/close-the-month.md']);
});

test('checkItems passes a well-formed library', () => {
  const root = makeRepo({
    'library/finance/close-the-month.md': ITEM('Close the month', 'finance'),
    'library/payroll/run-payroll.md': ITEM('Run payroll', 'payroll'),
  });

  assert.deepEqual(checkItems(root), []);
});

test('checkItems names each missing field separately', () => {
  const root = makeRepo({ 'library/finance/x.md': '---\ntitle: X\n---\n\nBody.\n' });

  const messages = checkItems(root).map((v) => v.message);

  assert.equal(messages.length, 3);
  assert.ok(messages.some((m) => m.includes('category')));
  assert.ok(messages.some((m) => m.includes('summary')));
  assert.ok(messages.some((m) => m.includes('updated')));
});

test('checkItems rejects a category that disagrees with the directory', () => {
  const root = makeRepo({ 'library/finance/x.md': ITEM('X', 'payroll') });

  const issues = checkItems(root);

  assert.equal(issues.length, 1);
  assert.equal(issues[0].rule, 'category');
  assert.match(issues[0].message, /payroll/);
  assert.match(issues[0].message, /finance/);
});

test('checkItems rejects an item sitting directly in library/ with no category directory', () => {
  const root = makeRepo({ 'library/loose.md': ITEM('Loose', 'finance') });

  const issues = checkItems(root);

  assert.equal(issues.length, 1);
  assert.equal(issues[0].rule, 'layout');
  assert.match(issues[0].message, /library\/<category>\/<item>\.md/);
});

// --- C1: the parser is 3b's lenient { values, structured } parser ---

test('parseFrontmatter unquotes a quoted scalar and returns the { values } shape', () => {
  const parsed = parseFrontmatter('---\ntitle: "Close the month"\ncategory: finance\n---\n');
  assert.equal(parsed.values.title, 'Close the month');
  assert.equal(parsed.values.category, 'finance');
});

test('checkItems ignores an item tags list while its required fields pass', () => {
  const root = makeRepo({
    'library/finance/x.md': '---\ntitle: X\ncategory: finance\nsummary: s\nupdated: 2026-07-22\ntags:\n  - a\n  - b\n---\n\nBody.\n',
  });

  assert.deepEqual(checkItems(root), []);
});

test('checkItems fails a required field written as a list, by name', () => {
  const root = makeRepo({
    'library/finance/x.md': '---\ntitle: X\ncategory:\n  - finance\nsummary: s\nupdated: 2026-07-22\n---\n\nBody.\n',
  });

  const issues = checkItems(root);

  assert.equal(issues.length, 1);
  assert.match(issues[0].message, /category must be a single-line/);
});

// --- Task 3c.2: the deterministic index generator ---

test('buildIndex groups by category, sorted, with no timestamp', () => {
  const root = makeRepo({
    'library/payroll/run-payroll.md': ITEM('Run payroll', 'payroll', 'Monthly run.'),
    'library/finance/close-the-month.md': ITEM('Close the month', 'finance', 'Month end.'),
    'library/finance/accruals.md': ITEM('Accruals', 'finance', 'Booking accruals.'),
  });

  const index = buildIndex(root);

  assert.equal(index, [
    '# Library index',
    '',
    'Generated by `node scripts/validate-library.mjs --write-index`. Do not edit by hand.',
    '',
    '## finance',
    '',
    '- [Accruals](../library/finance/accruals.md) — Booking accruals.',
    '- [Close the month](../library/finance/close-the-month.md) — Month end.',
    '',
    '## payroll',
    '',
    '- [Run payroll](../library/payroll/run-payroll.md) — Monthly run.',
    '',
  ].join('\n'));
});

test('buildIndex is byte-identical across runs', () => {
  const root = makeRepo({
    'library/finance/a.md': ITEM('A', 'finance'),
    'library/finance/b.md': ITEM('B', 'finance'),
    'library/payroll/c.md': ITEM('C', 'payroll'),
  });

  assert.equal(buildIndex(root), buildIndex(root));
});

test('buildIndex output does not depend on creation order', () => {
  const forward = makeRepo({
    'library/finance/a.md': ITEM('A', 'finance'),
    'library/payroll/b.md': ITEM('B', 'payroll'),
  });
  const reverse = makeRepo({
    'library/payroll/b.md': ITEM('B', 'payroll'),
    'library/finance/a.md': ITEM('A', 'finance'),
  });

  assert.equal(buildIndex(forward), buildIndex(reverse));
});

test('checkIndex reports a stale index and names the fix', () => {
  const root = makeRepo({
    'library/finance/a.md': ITEM('A', 'finance'),
    'docs/library-index.md': '# Library index\n\nout of date\n',
  });

  const issues = checkIndex(root);

  assert.equal(issues.length, 1);
  assert.equal(issues[0].rule, 'index-stale');
  assert.match(issues[0].message, /--write-index/);
});

test('checkIndex reports a missing index rather than throwing', () => {
  const root = makeRepo({ 'library/finance/a.md': ITEM('A', 'finance') });

  assert.equal(checkIndex(root)[0].rule, 'index-missing');
});

test('validateLibrary with write:true makes checkIndex clean', () => {
  const root = makeRepo({ 'library/finance/a.md': ITEM('A', 'finance') });

  validateLibrary(root, { write: true });

  assert.deepEqual(checkIndex(root), []);
  assert.equal(readFileSync(`${root}/${INDEX_PATH}`, 'utf8'), buildIndex(root));
});

// --- C5: two uncovered branches ---

test('checkItems reports an item with no frontmatter block at all', () => {
  const root = makeRepo({ 'library/finance/x.md': '# no frontmatter\n\nBody.\n' });

  const issues = checkItems(root);

  assert.equal(issues.length, 1);
  assert.equal(issues[0].rule, 'frontmatter');
  assert.match(issues[0].message, /no --- frontmatter/);
});

test('buildIndex falls back to the filename stem and empty summary when frontmatter is absent', () => {
  const root = makeRepo({ 'library/finance/orphan.md': '# no frontmatter\n' });

  const index = buildIndex(root);

  assert.match(index, /- \[orphan\]\(\.\.\/library\/finance\/orphan\.md\) — /);
  assert.equal(index.includes('undefined'), false);
});

// --- C2: the shared parser region stays byte-identical across the two validators ---

// The two validators deliberately do not share a module (each ships into a repo
// with no daftplate). This asserts the shared region stays byte-identical, so a
// one-sided bug fix fails here rather than in someone else's CI. A genuine
// divergence is allowed — delete this test and say why in the same commit.
const SHARED_START = '// Frontmatter contract, deliberately narrow';
const SHARED_END = '  return { values, structured };\n}';

const region = (url) => {
  const src = readFileSync(new URL(url, import.meta.url), 'utf8');
  const from = src.indexOf(SHARED_START);
  const to = src.indexOf(SHARED_END, from);
  assert.ok(from !== -1 && to !== -1, `shared region markers not found in ${url}`);
  return src.slice(from, to + SHARED_END.length);
};

test('both validators carry a byte-identical frontmatter parser', () => {
  assert.equal(
    region('../profiles/content-library/files/scripts/validate-library.mjs'),
    region('../profiles/design-vault/files/scripts/validate-vault.mjs'),
  );
});

// --- C3: the validator runs where it lands, and a fresh library is not clean
//     until its first index is generated ---

test('validate-library.mjs exits 1 with index-missing on a freshly scaffolded repo', () => {
  const dest = emptyDir();
  scaffold(ROOT, 'content-library', dest, values('dry-lib'));

  const result = spawnSync(process.execPath, [join(dest, 'scripts', 'validate-library.mjs'), dest], { encoding: 'utf8' });

  assert.equal(result.status, 1, `expected 1, got ${result.status}: ${result.stdout}`);
  assert.match(result.stderr, /index-missing/);
});

test('validate-library.mjs exits 0 after --write-index on a scaffolded repo', () => {
  const dest = emptyDir();
  scaffold(ROOT, 'content-library', dest, values('dry-lib'));

  const result = spawnSync(
    process.execPath,
    [join(dest, 'scripts', 'validate-library.mjs'), dest, '--write-index'],
    { encoding: 'utf8' },
  );

  assert.equal(result.status, 0, `exited ${result.status}: ${result.stderr}`);
});

// --- Task 3c.4: the validator must ship without daftplate ---

test('validate-library.mjs imports only node: builtins, because it ships without daftplate', () => {
  const source = readFileSync(
    new URL('../profiles/content-library/files/scripts/validate-library.mjs', import.meta.url),
    'utf8',
  );
  const specifiers = [...source.matchAll(/^import\s[^'"]*['"]([^'"]+)['"]/gm)].map((m) => m[1]);

  assert.ok(specifiers.length > 0, 'no imports found — did the file move?');
  const foreign = specifiers.filter((s) => !s.startsWith('node:'));
  assert.deepEqual(foreign, [], `these would not resolve in a scaffolded library: ${foreign.join(', ')}`);
});
