#!/usr/bin/env node
// Builds docs/code-map.md: a symbol index with line anchors, so an agent can
// grep the map and read one slice instead of a whole file.
// Usage: node scripts/code-map.mjs <repo> [--out <path>] [--min-bytes <n>]
//
// There is no parser here and there will not be one — this repo has no
// dependencies. The scanner is a line-oriented regex pass, and its contract is
// asymmetric: a missed symbol costs one grep, a mislocated symbol sends a
// reader to the wrong slice of a 775KB file. When a pattern is ambiguous, it
// does not match.
import { mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { dirname, extname, join } from 'node:path';
import { runCli } from './lib/cli.mjs';
import { walkFiles } from './lib/fs.mjs';

// Anchored at line start (allowing indentation), so `doSomething(function(){})`
// and `// function foo()` cannot match.
const DECLARATIONS = [
  { kind: 'function', re: /^[ \t]*(?:export[ \t]+)?(?:default[ \t]+)?(?:async[ \t]+)?function[ \t*]+([A-Za-z_$][\w$]*)/ },
  { kind: 'class', re: /^[ \t]*(?:export[ \t]+)?(?:default[ \t]+)?class[ \t]+([A-Za-z_$][\w$]*)/ },
  // `const f = (…) => …`, `const f = x => …`, `const f = function …`.
  // The right-hand side must look like a function; `const n = 42` must not match.
  {
    kind: 'function',
    re: /^[ \t]*(?:export[ \t]+)?(?:const|let|var)[ \t]+([A-Za-z_$][\w$]*)[ \t]*=[ \t]*(?:async[ \t]+)?(?:function\b|\([^)]*\)[ \t]*=>|[A-Za-z_$][\w$]*[ \t]*=>)/,
  },
];

const BANNER = /^[ \t]*(?:\/\/|\/\*|\*|#)[ \t]*[=\-*#]{3,}/;
// The trailing class includes \r so a CRLF file does not leave a carriage
// return glued to every captured section name.
const COMMENT_TEXT = /^[ \t]*(?:\/\/|\/\*|\*|#)[ \t]*(.*?)[ \t\r]*(?:\*\/)?[ \t\r]*$/;

export function scanSource(text) {
  const entries = [];
  const lines = text.split(/\r?\n/);

  for (let i = 0; i < lines.length; i += 1) {
    const raw = lines[i];

    if (BANNER.test(raw)) {
      // The name is the first non-banner comment text within the next two lines.
      // Unnamed banners are not navigable, so they are dropped.
      for (let j = i + 1; j <= i + 2 && j < lines.length; j += 1) {
        if (BANNER.test(lines[j])) continue;
        const name = (COMMENT_TEXT.exec(lines[j]) ?? [])[1];
        if (name) { entries.push({ line: i + 1, kind: 'section', name }); }
        break;
      }
      continue;
    }

    if (/^[ \t]*(?:\/\/|\*|\/\*)/.test(raw)) continue;

    for (const { kind, re } of DECLARATIONS) {
      const match = re.exec(raw);
      if (match) { entries.push({ line: i + 1, kind, name: match[1] }); break; }
    }
  }
  return entries;
}

const HTML_BLOCK = /^[ \t]*<(script|style|template)\b/i;

export function scanHtml(text) {
  const blocks = text.split(/\r?\n/).flatMap((raw, i) => {
    const match = HTML_BLOCK.exec(raw);
    return match ? [{ line: i + 1, kind: 'block', name: match[1].toLowerCase() }] : [];
  });
  return [...blocks, ...scanSource(text)].sort((a, b) => a.line - b.line);
}

const kb = (bytes) => `${(bytes / 1024).toFixed(1)} KB`;

// A banner comment can contain anything. Backticks and pipes would break the
// markdown row the symbol sits in.
const md = (s) => s.replace(/[`|]/g, '\\$&');

export function renderMap(files, meta = {}) {
  const out = [
    '# Code map',
    '',
    `Generated by \`scripts/code-map.mjs\` on ${meta.date ?? 'unknown date'}, indexing`,
    `source as of commit \`${meta.commit ?? 'unknown'}\`.`,
    '',
    'Do not edit by hand; your edits are overwritten on the next run. Grep this',
    'file for a symbol, then read only the lines around the anchor. Reading an',
    'indexed file whole defeats the purpose.',
    '',
    '**Before trusting an anchor, check that the map is current:**',
    '',
    '```',
    `git log -1 --format=%h -- ${PATHSPEC.map((p) => `'${p}'`).join(' ')}`,
    '```',
    '',
    'If that prints anything else, indexed source has changed since the map was',
    'generated and an anchor may point at the wrong slice — regenerate with',
    '`/code-map` rather than working around it.',
    '',
    'The stamp is the last commit that touched an indexed file, deliberately not',
    '`HEAD`: a map cannot name the commit that adds it, so stamping `HEAD` would',
    'report every freshly-committed map as stale.',
    '',
  ];

  for (const { path, bytes, lines, entries } of files) {
    out.push(`## \`${path}\``, '', `${kb(bytes)} · ${lines} lines`, '');
    if (!entries.length) {
      out.push('_no indexable symbols_', '');
      continue;
    }
    for (const { line, kind, name } of entries) {
      const label = kind === 'function' ? `\`${md(name)}()\`` : `**${md(name)}**`;
      out.push(`- \`${path}:${line}\` — ${label} (${kind})`);
    }
    out.push('');
  }
  return `${out.join('\n')}\n`;
}

export const INDEXABLE = new Set(['.js', '.mjs', '.cjs', '.gs', '.ts', '.tsx', '.jsx', '.html']);

// The same extension list as a git pathspec, so the freshness stamp and the
// check printed in the header can never drift from what is actually indexed.
// Git's default pathspec matching lets `*` cross directory separators, so
// `*.js` covers `lib/deep/thing.js`.
const PATHSPEC = [...INDEXABLE].map((ext) => `*${ext}`);

const DEFAULT_MIN_BYTES = 2048;

export function collectFiles(repoDir, opts = {}) {
  const minBytes = opts.minBytes ?? DEFAULT_MIN_BYTES;
  const visible = gitVisible(repoDir);

  // Size-filter BEFORE reading. statSync is cheap; reading a file and running
  // three regexes over every line only to discard it is not, and a repo with a
  // build output directory has hundreds of those.
  return walkFiles(repoDir)
    .filter(({ isDir, rel }) => !isDir && INDEXABLE.has(extname(rel).toLowerCase()))
    .filter(({ rel }) => !visible || visible.has(rel))
    .map(({ rel }) => ({ rel, bytes: statSync(join(repoDir, rel)).size }))
    .filter(({ bytes }) => bytes >= minBytes)
    .map(({ rel, bytes }) => {
      const text = readFileSync(join(repoDir, rel), 'utf8');
      return {
        path: rel,
        bytes,
        lines: text.split(/\r?\n/).length,
        entries: extname(rel).toLowerCase() === '.html' ? scanHtml(text) : scanSource(text),
      };
    })
    .sort((a, b) => b.bytes - a.bytes || a.path.localeCompare(b.path));
}

// No `shell: true`. The shell re-parses the joined command line, so a repoDir
// containing a space word-splits and git exits 128 — which is how
// `x:\Projects\Torn Bookie Live Scores` silently mapped as commit `unknown`.
// Windows resolves a bare `git` to `git.exe` without a shell; only `.cmd`
// shims need one, and this is not one.
const git = (repoDir, args) => {
  const r = spawnSync('git', ['-C', repoDir, ...args], { encoding: 'utf8' });
  return r.status === 0 ? r.stdout : null;
};

/**
 * Short sha of the last commit that touched an indexed file, or 'unknown'
 * outside a git repo. Never throws.
 *
 * Not `rev-parse HEAD`. The map is committed after it is generated, so a HEAD
 * stamp is one commit behind the moment it lands, and the freshness check the
 * header prescribes then fails on the very commit that generated the map — a
 * false positive precisely when the map is most trustworthy. Stamping the last
 * source-touching commit is stable across committing the map, across docs-only
 * commits, and across a squash merge, while still moving the instant an
 * indexed file changes.
 */
export function sourceCommit(repoDir) {
  return git(repoDir, ['log', '-1', '--format=%h', '--', ...PATHSPEC])?.trim() || 'unknown';
}

/**
 * Repo-relative paths git does not ignore, or null outside a git repo.
 *
 * EXCLUDED_DIRS is a fixed list and cannot know about a repo's own ignores, so
 * without this a stale worktree copy under an ignored directory is indexed
 * beside the real file and every symbol grep returns two plausible anchors.
 * The filter is "not ignored" rather than "tracked": a freshly scaffolded repo
 * has committed nothing yet and must still map.
 */
function gitVisible(repoDir) {
  const out = git(repoDir, ['ls-files', '-z', '--cached', '--others', '--exclude-standard']);
  return out === null ? null : new Set(out.split('\0').filter(Boolean));
}

export function buildCodeMap(repoDir, opts = {}) {
  const files = collectFiles(repoDir, opts);
  const path = join(repoDir, opts.out ?? 'docs/code-map.md');
  mkdirSync(dirname(path), { recursive: true });
  const meta = {
    commit: opts.commit ?? sourceCommit(repoDir),
    date: opts.date ?? new Date().toISOString().slice(0, 10),
  };
  writeFileSync(path, renderMap(files, meta), 'utf8');
  return {
    path,
    commit: meta.commit,
    files: files.length,
    symbols: files.reduce((n, f) => n + f.entries.length, 0),
  };
}

function main(argv) {
  const args = argv.slice(2);
  const repo = args.find((a) => !a.startsWith('--'));
  if (!repo) {
    console.error('usage: node scripts/code-map.mjs <repo> [--out <path>] [--min-bytes <n>]');
    return 2;
  }
  const flag = (key) => {
    const i = args.indexOf(`--${key}`);
    return i === -1 ? undefined : args[i + 1];
  };
  const minBytesArg = flag('min-bytes');
  const { path, files, symbols } = buildCodeMap(repo, {
    out: flag('out'),
    minBytes: minBytesArg === undefined ? undefined : Number(minBytesArg),
  });
  console.log(`${path} — ${files} file(s), ${symbols} symbol(s)`);
  return 0;
}

export { main };
runCli(import.meta.url, main);
